### PR TITLE
Removed user from Docker file to avoid permission conflicts using loc…

### PR DESCRIPTION
**Pull request by ljl**
…al volume

### CODE REVIEW

**Comment by drerik** [comment]
This is a container ment for production use, and a application should never run as root unless i has to do it. Removing the dedicated user for enonic xp is a very bad solution for file access problems.

 "live" data as stored in the repo folder should run inside a volume container instead.
As an alternative, you can chown your storage folder to the same uid as the enonic-xp user inside the container. Aka. do a "chown 1337 -R /you/storage/folder" on the storage folder, it will make it so that you can save data fro the xp container to hosts filesystem. But this is the second best sollution.

**Comment by ljl** [comment]
Docker is a contained environment with a limited root. Other official docker images (wordpress, postgres, django etc) all run as root inside the container.

I know you can use a volume container, but it doesnt change the fact that the permissions get messed up if you do.

An example
docker run -d --name xp-home -v /Users/lassejl/enonic:/enonic-xp/home/ enonic/xp-home
docker run -it -p 8080:8080 --volumes-from xp-home --name xp-app enonic/xp-app:6.5.2 /bin/bash
./launcher.sh &
ls -ld /enonic-xp/home

Returns:
drwxr-xr-x 1 1000 staff 102 May  3 10:51 enonic-xp/home 

The home folder becomes owned by a non-existing user with id 1000.

After investigating this for a while it works if you mount the xp-home container to the $XP_HOME/deploy, but not the root of XP_HOME. This means you can't edit config/view logs from outside the container. If that is the purpose however, then the naming of xp-home is confusing.

**Comment by jonasws** [comment]
@drerik Is it still your opinion to fiddle around with the permissions of the $XP_HOME directory?. Isn't the data volume container approach about to become obsolete in favor of named data volumes? It also makes it difficult to deploy the image to say, AWS Elastic Beanstalk, as you have no way of tweaking permission in said context.

That said, it would of course not be any problem for anyone to simply create their own xp-app image that would better suit their needs, but since I would assume many developers end up here, it would be good to have these topics "aired out" a little more.

UPDATE: I resarched this some more, and data volume containers are no longer the recommended practice when dealing with volumes, as stated [here](https://github.com/moby/moby/issues/20465)

**Comment by drerik** [comment]
Hi @jonasws.
We still wan't to run Enonic XP as its own user instead of root.

Creating a docker volume instead of setting up a data volume container is the preferred method for docker, and has been for like that for a while. Improving the docker image is on the todo list, and hope to do it by this summer.

**Comment by jonasws** [comment]
I see other images doing it this way, such as the official MySQL and Redis images, so I very much agree with the matter of running Enonic XP as non-root. I am just trying to figure out why so many permission issues arise when not using the volume container approach. It may have to do with how you assign a custom UID. See the [redis image](https://github.com/docker-library/redis/blob/24aa66d88990e0eeec71bd39862744fdb7b862e4/3.0/Dockerfile) for an example of how they not necessarily go all the way and assign a custom UID to the dedicated user.

**Pull request closed without merging**
